"""avatar row

Revision ID: 928532dbc0d6
Revises: ca7f7fc8861f
Create Date: 2023-04-18 11:36:02.620927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928532dbc0d6'
down_revision = 'ca7f7fc8861f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
